
# @baseUrl = 'https://api.teleport.org/api/,'

GET https://countriesnow.space/api/v0.1/countries/




#==================================================================
# WORKING API'S
#==================================================================
# https://restcountries.com/v2/all
# (country names, flag images)

# https://documenter.getpostman.com/view/1134062/T1LJjU52#abee09ea-aeb9-479c-b970-81d909c2a58c
#Population /Location / Flag / Currencies / Capital / Cities / Codes / Filter / States / More
# https://countriesnow.space/api/v0.1/countries/population/cities
# https://countriesnow.space/api/v0.1/countries/currency
# https://countriesnow.space/api/v0.1/countries/capital


# https://restcountries.eu/rest/v2/ *** DID NOT WORK

########### POTENTIAL API - BUT COULD NOT WORK OUT HOW TO ACCESS...

#https://www.programmableweb.com/api/clickbank-images-rest-api-v13
#The ClickBank Images API generates lists of images related to particular accounts. ClickBank is a worldwide digital sales portal for products created by entrepreneurs. The company distributes a wide variety of digital lifestyle products to more than 190 countries. The API returns responses in JSON or XML format.



